language: python
python:
  - "3.8.10"
install:
  - pip install -r requirements.txt
script:
  - python3 -m unittest discover -s "./tests/unit/" -p "test_*.py"
  - python3 -m unittest discover -s "./tests/integration/" -p "test_*.py"
  - python3 -m unittest discover -s "./tests/system/" -p "test_*.py"
  - flake8